# This file was generated by GoReleaser. DO NOT EDIT.
cask "calvin" do
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_amd64.tar.gz"
      sha256 "f5281e808afbf4a11945c2a4d2ad0f30ed223762e23924e544c244aba3b2c466"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_arm64.tar.gz"
      sha256 "422fe2bf26b01876c9f3a7201220bcb353930e68a449bdf35662ff1263d34dea"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_amd64.tar.gz"
      sha256 "9863d7bec383abc7052cfb0f8d77da3a94835d1ebf2dc56d745052c162edcf9a"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_arm64.tar.gz"
      sha256 "f7748f02ea0a790fe79e1725a51a9193d1a19b8ab8df0bc12ac63a6eda2e7ffb"
    end
  end

  name "calvin"
  desc "Programmable calendar hooks for your Mac"
  homepage "https://github.com/andrew8088/calvin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calvin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calvin"]
  end

  # No zap stanza required

end
