# This file was generated by GoReleaser. DO NOT EDIT.
cask "calvin" do
  version "0.9.0"

  on_macos do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_amd64.tar.gz"
      sha256 "90aa9639cc43f6d7ed01806c2d0d39d471b8820085cc984742aaea2728fff42e"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_arm64.tar.gz"
      sha256 "71154d26e17031b20d58e1d4d6b3215bb1556c01af8ec7de55daaabf04090e23"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_amd64.tar.gz"
      sha256 "4a4223c810e2b8b98a7e34b64a076ee7d485ff55250dc2727358eb767ccfca76"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_arm64.tar.gz"
      sha256 "6ff7916210ec9faef9502295d5f74fe8c1ba9f357539ed0a6c04bfdb2037cbc7"
    end
  end

  name "calvin"
  desc "Programmable calendar hooks for your Mac"
  homepage "https://github.com/andrew8088/calvin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calvin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calvin"]
  end

  # No zap stanza required

end
