# This file was generated by GoReleaser. DO NOT EDIT.
cask "calvin" do
  version "0.2.0"

  on_macos do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_amd64.tar.gz"
      sha256 "2bfd3d4a43b47cfeb57c3d3ffde8505e59c9261440b779ece0edb6d26e6d2b52"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_darwin_arm64.tar.gz"
      sha256 "0d4ecae5f1b13e0cff4d41513b4cd7a2656b19e33eb756f8b4c2323e2e980b0a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_amd64.tar.gz"
      sha256 "7fbbbb84e6a8fcb43afa2107516f0d3918248e7b73440c18a7758cf2b772ba3e"
    end
    on_arm do
      url "https://github.com/andrew8088/calvin/releases/download/v#{version}/calvin_#{version}_linux_arm64.tar.gz"
      sha256 "d68c0bcb1ece928e6cb7f84e8e1513b6e0a45e1eef6aeff74c295ad2fb836c93"
    end
  end

  name "calvin"
  desc "Programmable calendar hooks for your Mac"
  homepage "https://github.com/andrew8088/calvin"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "calvin"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/calvin"]
  end

  # No zap stanza required

end
